[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "A-Maze-ing generator package for the 42 Common Core"
readme = "README.md"
requires-python = ">=3.10"
license = MIT

authors = [
	{ name = "kochniak", email = "kochniak@student.42.fr" },
	{ name = "jwira", email = "jwira@student.42.fr" }
]
dependencies = []

[tool.setuptools.packages.find]
include = ["mazegen*"]
